version: "3.8"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  mysql:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
  app:
    build: .
    command: yarn run start:prod
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - mysql